//
// Copyright (c) Sharon Fox (sharon at sharonfox dot dev)
//
// Distributed under the MIT License. (See accompanying file LICENSE)
//


#define DEF_DYNAMICOBJECT_FIRE			1
#define DEF_DYNAMICOBJECT_FISH			2
#define DEF_DYNAMICOBJECT_FISHOBJECT	3
#define DEF_DYNAMICOBJECT_MINERAL1		4
#define DEF_DYNAMICOBJECT_MINERAL2		5
#define DEF_DYNAMICOBJECT_ARESDENFLAG1	6
#define DEF_DYNAMICOBJECT_ELVINEFLAG1	7
#define DEF_DYNAMICOBJECT_ICESTORM		8
#define DEF_DYNAMICOBJECT_SPIKE			9
#define DEF_DYNAMICOBJECT_PCLOUD_BEGIN	10
#define DEF_DYNAMICOBJECT_PCLOUD_LOOP	11
#define DEF_DYNAMICOBJECT_PCLOUD_END	12
#define DEF_DYNAMICOBJECT_FIRE2			13
#define DEF_DYNAMICOBJECT_FIRE3			14 // FireBow

#ifdef DEF_EQUILIBRIUM_PROJECT
#define DEF_DYNAMICOBJECT_STATUE1		15 // Avatar quest
#define DEF_DYNAMICOBJECT_STATUE2		16 // Avatar quest
#define DEF_DYNAMICOBJECT_STATUE3		17 // Avatar quest
#define DEF_DYNAMICOBJECT_STATUE4		18 // Avatar quest
#define DEF_DYNAMICOBJECT_STATUE5		19 // Avatar quest
#define DEF_DYNAMICOBJECT_STATUE6		20 // Avatar quest
#define DEF_DYNAMICOBJECT_STATUE7		21 // Avatar quest
#define DEF_DYNAMICOBJECT_CHEST1		22
#define DEF_DYNAMICOBJECT_CHEST2		23
#define DEF_DYNAMICOBJECT_BARREL		24 
#define DEF_DYNAMICOBJECT_OBELISK1		25
#define DEF_DYNAMICOBJECT_OBELISK2		26
#define DEF_DYNAMICOBJECT_OBELISK3		27

#endif
